### ISSUE TITLE
Support tax before discount

### ISSUE THREAD

**Issue by JReissmueller** [blesta/pricing#16]
Currently tax is calculated for item prices after discounts are applied.  There should be an options to calculate tax before discounts are applied.

**Comment by tysonphillips** [comment]
The current behavior applies discounts to taxes, for example:
$1.00 taxed at 5% with a 10% discount is:
(1.00 * (1 - 0.1)) + [(1.00 * (1 - 0.1)) * 0.05]
Subtotal: $1.00
Discount: $0.10
Tax: $0.045
Total: $0.945

This update would simply not apply discounts to taxes. The above example would change to:
(1.00 * (1 - 0.1)) + (1.00 * 0.05)
Subtotal: $1.00
Discount: $0.10
Tax: $0.05
Total: $0.95
